# Generated by Django 4.1.3 on 2022-11-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenscriptEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proteinName', models.CharField(max_length=255)),
                ('uniprot', models.CharField(max_length=10)),
                ('resind', models.IntegerField()),
                ('sequence', models.TextField()),
            ],
        ),
    ]
