# Generated by Django 4.1.3 on 2022-11-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genscriptentry',
            old_name='sequence',
            new_name='aminoSequence',
        ),
        migrations.RemoveField(
            model_name='genscriptentry',
            name='resind',
        ),
        migrations.AddField(
            model_name='genscriptentry',
            name='residueIndex',
            field=models.IntegerField(default=1),
        ),
    ]
