# Generated by Django 4.1.3 on 2022-11-09 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_sequence_genscriptentry_aminosequence_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genscriptentry',
            old_name='aminoSequence',
            new_name='amino_sequence',
        ),
        migrations.RenameField(
            model_name='genscriptentry',
            old_name='proteinName',
            new_name='protein_name',
        ),
        migrations.RenameField(
            model_name='genscriptentry',
            old_name='residueIndex',
            new_name='residue_index',
        ),
        migrations.RenameField(
            model_name='genscriptentry',
            old_name='uniprot',
            new_name='uniprot_id',
        ),
    ]
