# Generated by Django 4.1.3 on 2022-11-11 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_aminosequence_genscriptentry_amino_sequence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genscriptentry',
            name='dna_sequence',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
